language: ruby
rvm:
- 2.3.3
before_install:
  - npm install
script:
  - ls
  - node -pe "require('./package.json').version"
  - npm run travis
  - ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: _site
